### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [MateusRodCosta/Share2Storage#13]
https://gitlab.com/fdroid/fdroiddata/-/jobs/5916419780#L2102

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/f83b3f21376174bc71fe34c9a637d3fc5453cc39

**Comment by licaon-kter** [comment]
@linsui I guess this is https://gitlab.com/fdroid/fdroiddata/-/issues/3138

but https://github.com/MateusRodCosta/Share2Storage/blob/v1.0.0/app/build.gradle.kts#L76 

what the?

**Comment by linsui** [comment]
Maybe only 1.5.6 works. :)

**Comment by MateusRodCosta** [comment]
@licaon-kter What should I do then?
A 1.0.0 release exclusive to F-Droid with different Kotlin and Jetpack Compose compiler versions?

**Comment by MateusRodCosta** [comment]
Maybe the issue is related to this:

```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
Binary files /tmp/tmp0xvmwemh/tmp_binaries_com.mateusrodcosta.apps.share2storage_14.binary/content/assets/dexopt/baseline.prof and /tmp/tmp0xvmwemh/_tmp_tmp0xvmwemh_sigcp_com.mateusrodcosta.apps.share2storage_14/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmp0xvmwemh/tmp_binaries_com.mateusrodcosta.apps.share2storage_14.binary/content/classes.dex and /tmp/tmp0xvmwemh/_tmp_tmp0xvmwemh_sigcp_com.mateusrodcosta.apps.share2storage_14/content/classes.dex differ
==== detail end ====
````

At least the baseline profile seems to be related to the AGP version: https://developer.android.com/topic/performance/baselineprofiles/overview#recommended-versions

Not sure about why classes.dex differ though.

**Comment by linsui** [comment]
The baseline file has a hash of the classes.dex file.

**Comment by MateusRodCosta** [comment]
Tried to rebuild a new APK on my system, apparently the files inside the APK are the same between 1.0.0 published and that new build (if we consider the size of the changes would show up when enabling file-by-file patch size).

![Captura de tela de 2024-01-12 10-36-39](https://github.com/MateusRodCosta/Share2Storage/assets/24463334/3c455540-b3ba-4767-b832-effc3470f268)

**Comment by licaon-kter** [comment]
@MateusRodCosta can you tell what you've changed and host an APK for us to compare against?

**Comment by MateusRodCosta** [comment]
@licaon-kter Hi, please consider the two APKs inside the ZIP.

The signed universal APK Google Play generated from the App bundle is the one called `14.apk`, a new signed APK build is called `app-release.apk`.

[SaveLocally-14-APKs.zip](https://github.com/MateusRodCosta/Share2Storage/files/13929022/SaveLocally-14-APKs.zip)

Please compare them to whatever F-Droid is building, AFAIK there should be no differences.

**Comment by licaon-kter** [comment]
Will do asap


Do note that the Google APK can't never be repro as Google injects a bunch of junk. :(

**Comment by MateusRodCosta** [comment]
> Do note that the Google APK can't never be repro as Google injects a bunch of junk. :(

No problem, I'm mostly just attaching it so it can help in the comparison, as it's likely the closest we can get to what was actually shioped to users via Google Play.

Though the only thing I know that Google Play adds is frosting/SourceStamp along with signing with their own keys.

**Comment by MateusRodCosta** [comment]
@licaon-kter Oh yeah, btw, I was gonna open a issue on F-droid repo on it, but since we already have this one...

Could you take a look into adding donation information for the F-Droid app page once version 1.0.0 is uploaded?

You can find the donation information at https://github.com/MateusRodCosta/Share2Storage/blob/main/.github/FUNDING.yml, but if it's only possible to add once consider only adding https://www.mateusrodcosta.dev/donate/

**Comment by licaon-kter** [comment]
The FUNDING.yml is parsed by default, there's no need to add extra entries.

**Comment by MateusRodCosta** [comment]
@licaon-kter Anu update on what might be the cause?

**Comment by MateusRodCosta** [comment]
@licaon-kter Any updates? I'm already planning on a few bug fixes for 1.0.1 release so, if F-droid requires some code changes, I can do them in that release.

**Comment by licaon-kter** [comment]
Didn't get a chance to test :(

**Comment by MateusRodCosta** [comment]
@licaon-kter  I released version 1.0.1 (https://github.com/MateusRodCosta/Share2Storage/releases/tag/v1.0.1), please check if it works now.

**Comment by licaon-kter** [comment]
https://monitor.f-droid.org/builds/log/com.mateusrodcosta.apps.share2storage/15#site-footer :tada:

**Comment by licaon-kter** [comment]
ref: https://monitor.f-droid.org/builds/log/com.mateusrodcosta.apps.share2storage/17#site-footer

difflog: [save17.log](https://github.com/MateusRodCosta/Share2Storage/files/14823874/save17.log)

**Comment by MateusRodCosta** [comment]
@licaon-kter I have no idea why is it failing. Is it the Compose compiler again?

**Comment by MateusRodCosta** [comment]
@licaon-kter Please retry with [v1.2.1](https://github.com/MateusRodCosta/Share2Storage/releases/tag/v1.2.1)!

**Comment by licaon-kter** [comment]
you've tagged https://github.com/MateusRodCosta/Share2Storage/releases/tag/v1.2.2 from https://github.com/MateusRodCosta/Share2Storage/commit/ad938f41613e433f69a05317015db0056ceddae5

but the apk was built from https://github.com/MateusRodCosta/Share2Storage/commit/65ac993bc2ac57d40b130aef3ced1e2a678afb9a ?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6821803395#L1014

fixed manually, https://gitlab.com/fdroid/fdroiddata/-/commit/5485d10b7bcaa931edada285a87d57b34b0efa0e

please in the future publish the APK built from the same tagged commit

**Comment by MateusRodCosta** [comment]
@licaon-kter Hi, my mistake, fastlane and me too update it so I made a new commit post publishing to Google Upgrade via fastlane deploy.

I meant to then checkout the previous commit for the tag to build the release certain but ended forgetting, though it shouldn't be much different due to only the Gemfile.lock really changing
