### ISSUE TITLE
Optionally capture ACTION_VIEW

### ISSUE THREAD

**Issue by CyberShadow** [MateusRodCosta/Share2Storage#19]
Some apps force opening files with ACTION_VIEW, and do not give you an option to save the file.

It would be nice if it was possible to handle this action as well.

Thanks!

**Comment by CyberShadow** [comment]
This does it:

```diff
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 48e55b4..323fb7c 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -25,6 +25,7 @@
 
             <intent-filter>
                 <action android:name="android.intent.action.SEND" />
+                <action android:name="android.intent.action.VIEW" />
 
                 <category android:name="android.intent.category.DEFAULT" />
 
diff --git a/app/src/main/kotlin/com/mateusrodcosta/apps/share2storage/DetailsActivity.kt b/app/src/main/kotlin/com/mateusrodcosta/apps/share2storage/DetailsActivity.kt
index 4e4daf6..ebb8a94 100644
--- a/app/src/main/kotlin/com/mateusrodcosta/apps/share2storage/DetailsActivity.kt
+++ b/app/src/main/kotlin/com/mateusrodcosta/apps/share2storage/DetailsActivity.kt
@@ -81,13 +81,16 @@ class DetailsActivity : ComponentActivity() {
     }
 
     private fun handleIntent() {
-        if (intent.action == Intent.ACTION_SEND) {
-            val fileUri: Uri? =
+        if (intent.action == Intent.ACTION_SEND || intent.action == Intent.ACTION_VIEW) {
+            var fileUri: Uri? =
                 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) intent.getParcelableExtra(
                     Intent.EXTRA_STREAM,
                     Uri::class.java
                 )
                 else @Suppress("DEPRECATION") intent.getParcelableExtra(Intent.EXTRA_STREAM)
+            if (fileUri == null) {
+                fileUri = intent.data;
+            }
             Log.d("fileUri", fileUri.toString())
             uriData = getUriData(contentResolver, fileUri)
 
```

Probably should be optional, which means that the `intent-filter` needs to be set programmatically, so maybe a bit more code than that. 

Or maybe there's no reason why it should be optional.

**Comment by MateusRodCosta** [comment]
@CyberShadow Hey, thanks for the feature request!

Well, since it's just a bit outside of the main use case but adjacent to it, I believe I could do it but it would have to be gated behind a preference.

So, yeah, I will have to figure out how to dynamically add (or at least enable) new intent filters.

Thanks for the code excerpt, I will take a look into this in the near future.

**Comment by CyberShadow** [comment]
Thanks for considering it.

For the record, the use case is that for some reason, my bank app does not allow saving/sharing/exporting receipts - only viewing them.

The above patch allowed me to actually save the receipt and attach it to a customs declaration.

**Comment by MateusRodCosta** [comment]
@CyberShadow So, I did search about what would be the best way to programmatically add and remove intent filters...
The most interesting option I found was to use activity aliases and use the enabling/disabling of components based on a setting.

Unfortunately I'm currently running on issue trying to get this working, but I believe I made some progress.

**Comment by MateusRodCosta** [comment]
@CyberShadow I managed to implement this and it will make it into the next version!
The next version is planned for either the end of this month or start of next month, in the mean time you can compile the current dev branch yourself.

**Comment by CyberShadow** [comment]
Excellent!

Does it need testing?

I'm surprised that your diff almost doesn't touch `DetailsActivity` like mine did.

**Comment by MateusRodCosta** [comment]
> I'm surprised that your diff almost doesn't touch `DetailsActivity` like mine did.

Actually, I got so distracted focusing on the manifest (the activity alias) and on the setting that I might have forgot completely to edit the DetailsActivity code that actually grabs the intent.

I will fix that in a  bit.

**Comment by MateusRodCosta** [comment]
> Actually, I got so distracted focusing on the manifest (the activity alias) and on the setting that I might have forgot completely to edit the DetailsActivity code that actually grabs the intent.

Should be fixed now.

> Does it need testing?

Sure, feel free to test it!
