### ISSUE TITLE
Support all file formats

### ISSUE THREAD

**Issue by jm355** [MateusRodCosta/Share2Storage#28]
I'm trying to export my bookmarked locations in magic earth, which is done by sharing a file called favorites.xlm. Only a small fraction of the normal apps show up as options, and share2storage is not one of them

**Comment by MateusRodCosta** [comment]
Hi, at the moment these are the file formats (actually the mime types) supported:

https://github.com/MateusRodCosta/Share2Storage/blob/a0f9fc7ced67b67d48b5894f324eea4adcaa12ab/app/src/main/AndroidManifest.xml#L36-L40

I would assume a xml file would be registered under `text/*`?
Are you sure it's sending the xml as a file and not sending the body of the xml on the intent?

**Comment by jm355** [comment]
So one interesting thing, when I share to syncthing to save it, syncthing calls the file "Favourites.xlm.bin", where the share menu didn't have .bin on the end. I'm trying to get it saved and then I'll try that command in termux

**Comment by jm355** [comment]
In the system (grapheneos) file manager, the type is BIN file

**Comment by jm355** [comment]
```
$ file --mime Favourites.xlm
Favourites.xlm: application/vnd.sqlite3; charset=binary
```

**Comment by jm355** [comment]
Imo, the best bet is to open it up to save any/everything, and then let people report bugs on the ones that don't work

**Comment by MateusRodCosta** [comment]
Hi, I pushed to the dev branch this change. 

It will take a while to push a new release to Play Store and F-Droid since I plan on also redoing the screenshots. 

If you are able and know how to build an Android app, consider building the dev branch and checking if it fixes your issue.

**Comment by jm355** [comment]
Latest update worked with the magic earth favorites export as expected, thanks!
