### ISSUE TITLE
b8897db0-2441-47fb-b854-be3b80c2927a

### ISSUE THREAD

**Issue by MrQueen132** [MateusRodCosta/Share2Storage#30]

**Comment by MateusRodCosta** [comment]
No idea what this means

**Comment by MateusRodCosta** [comment]
Oh, it's the PIX key for donation.

That's only relevant if you're Brazilian, you would make a Pix transaction (which is monetary transaction that goes from your account directly to mine) through your Brazilian bank app.

I decided to use a randomly generated key so I didn't have to share my phone number, email address or CPF (which is like America's SSN)
