### ISSUE TITLE
Details/preview page briefly shown despite settings

### ISSUE THREAD

**Issue by Cwpute** [MateusRodCosta/Share2Storage#42]
When the setting is set to "Directly open file picker" and "No preview", the app still shows the details page for a briefqmoment after the file was saved, which is unnecessary and a bit confusing.

**Comment by MateusRodCosta** [comment]
That's a bit complex though.
The Activity that receives the file is connected to that UI.
The open you mentioned just immediately runs the same code that the FAB for saving file does.

So, the best I can do is either immediately closing the activity (which I don't know if could cause problems with the file saving code) or somebody suggested to change the screen, and I got a bit of that in 9cbcd10d7fb281b998464dcc19b3ee010ca2755d which just makes a screen saying "Saving file..."

**Comment by Cwpute** [comment]
I don't know much about the ins and outs of how running an app works so most of what you said i didn't understand 😂
I can try to ask relevant questions though !

Do you need your app to be in focus for the activity to run ? if not then you could keep your app out of focus so whatever window might show it doesn't for the user.

That "Saving file…" message might be a good enough work around, but i think a toast message would probably be enough for that purpose.

**Comment by MateusRodCosta** [comment]
Hi, so for this i will go with the "Skip File Details" option replacing the screen contents with "Saving file" and also immediately opening the file picker.

This is already working and should make its way to the next release.
The underlying screen should appear for just around less than a second.
