### ISSUE TITLE
Allow for file rename

### ISSUE THREAD

**Issue by licaon-kter** [MateusRodCosta/Share2Storage#5]

**Comment by MateusRodCosta** [comment]
Not sure what is asked here.

When the file picker to save the file is shown it is filled with the name of the original file but at that point you can set whatever name you want.

Unless it broke at some point or it's a restriction on older Androids, it should already work fine as it is handled the DocumentsUI (i.e. the APK behind the file picker).

**Comment by licaon-kter** [comment]
> When the file picker to save the file is shown 

ah indeed, it's smaller in in the lower part of the screen :)
