### ISSUE TITLE
Allow to save in a default/last folder

### ISSUE THREAD

**Issue by licaon-kter** [MateusRodCosta/Share2Storage#6]
eg. have _"Save in default"_ or _"Save in last (/last path/)"_ and _"Save"_ (this one lets you choose, like now)

**Comment by MateusRodCosta** [comment]
Hmm, I believe I can approach this in two ways:

1) I could make the current save floating button open a small menu where it keeps the current button for normal save and extra buttons for other options (although I might not necessarily keep using floating action button)
2) Create a Settings screen and house some options there (at the very least whether to Always open on default and where is the Default)
3) A combination of the previous two options

In anyway I will take a look this week, I was already planning on starting working on the new version.

**Comment by MateusRodCosta** [comment]
So, I have taken a look into this recently.

As far as I noticed it uses the last folder by default, so it is just a question of making some UI for the user to choose the custom dir or unset it (which resets to default) and then changing the code that triggers the file picker appropriately.

I did manage to do the UI on the Settings page, however I am having a few issues on how to integrate the extra piece of code for the file picker to start in a specific folder.

Still, I will try to get it done in the coming days.

**Comment by MateusRodCosta** [comment]
I'm currently hitting a wall on this one.
I figured out how to extend the [CreateDocument](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.CreateDocument#CreateDocument(kotlin.String)) class to be able to add the [EXTRA_INITIAL_URI](https://developer.android.com/reference/android/provider/DocumentsContract.html#EXTRA_INITIAL_URI) parameter to the intent, however as far as I managed to test it is completely ignored.

I will give a better try tomorrow, but it will be a shame if it's somehow broken as I already spent a lot of time on the rest of the plumbing for this to work. =/

**Comment by MateusRodCosta** [comment]
This is now implemented in commit 5fd964eb31a607444cedc12b96d6c2b9f8035ea8.

The UI is as follow:

![Screenshot_20240109_144129](https://github.com/MateusRodCosta/Share2Storage/assets/24463334/9d080d79-926d-4b45-aaf9-54a754352639)

![Screenshot_20240109_144152](https://github.com/MateusRodCosta/Share2Storage/assets/24463334/4b232d9a-2c90-4813-82d2-e0e8be8c3294)

If you believe it should implemented a different way, please reopen the issue.
